### ISSUE TITLE
[asciidoc] When using inline generated images

### ISSUE THREAD

**Issue by rnwolf** [getnikola/plugins#309]
Hi

I am keen to use inline images, such as the following in my asciidoc source files.

https://asciidoctor.org/news/2014/02/18/plain-text-diagrams-in-asciidoctor/

I have installed https://plugins.getnikola.com/v8/asciidoc/
https://github.com/getnikola/plugins/blob/master/v8/asciidoc/asciidoc.py

and the ruby versions of asciidoctor and asciidoctor-diagram.

When using the commandline the following:

$ asciidoctor -r asciidoctor-diagram doc.adoc

will produce a html files plus any number of image files, png, svg etc.

Any suggestions on how I might get these images moved to the relevant output folder?

The current plugin works fine on the text portion of the source file.

**Comment by Kwpolska** [comment]
That isn’t going to be easy to do “right”. If you can come up with filenames before the file is compiled, and could somehow produce tasks for Nikola, then it could write to `cache/`, and Nikola would copy it from there, with two custom plugins. An alternative would be for asciidoctor to put these files directly in `output/`, but files untracked by Nikola would make `nikola check -f` not work for your site. Nikola’s architecture means that compiling one input file into many output files (without Nikola knowing how many and with what names) is not really possible.

Some easier possibilities include:

1. Have the graphs embedded in HTML instead of producing separate files, that makes a lot of sense for SVG but not so much for PNG. asciidoctor should be able to do this; if it isn’t, that shouldn’t be hard to contribute to them.
2. Have a Nikola plugin to create standalone `.svg` or `.png` files out of separate `.dot` files and embed them as images.
