### ISSUE TITLE
[planetoid] comprehension question on updating feed

### ISSUE THREAD

**Issue by encarsia** [getnikola/plugins#377]
Hey,

I have an issue understanding the planetoid plugin. It works so far as the site builds but given the fact being static it of course doesn't update which also makes the PLANETOID_REFRESH option kind of pointless...?

So my understanding is that I'll have to build and deploy this planet on a schedule (cron).

Can you give me a clue here?

Regards.

**Comment by Kwpolska** [comment]
The point of `PLANETOID_REFRESH` is to avoid querying RSS feeds on every build, eg. when you’re tinkering with the layout. If you run `nikola build` twice in a row, your feeds will not be fetched on the second run (due to `PLANETOID_REFRESH` seconds not passing).

To build the site, you need to use `cron` or something else. The time between builds should be bigger than `PLANETOID_REFRESH` + average build time, and I would probably recommend building only every few hours.

**Comment by encarsia** [comment]
Thanks, that was helpful.
